import { MODEL_CATEGORIES, PROVIDERS } from './constants'

export const STATIC_MODELS = [
  {
    id: 'anthropic/claude-sonnet-4-20250514',
    name: 'Claude Sonnet 4',
    provider: PROVIDERS.ANTHROPIC,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.CREATIVE,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 200_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 3.0, completionPerMillion: 15.0 },
  },
  {
    id: 'anthropic/claude-3-5-haiku-20241022',
    name: 'Claude 3.5 Haiku',
    provider: PROVIDERS.ANTHROPIC,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.FAST,
      MODEL_CATEGORIES.GENERAL,
      MODEL_CATEGORIES.VISION,
    ],
    contextWindow: 200_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.8, completionPerMillion: 4.0 },
  },
  {
    id: 'anthropic/claude-opus-4-20250514',
    name: 'Claude Opus 4',
    provider: PROVIDERS.ANTHROPIC,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.CREATIVE,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 200_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 15.0, completionPerMillion: 75.0 },
  },
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: PROVIDERS.OPENAI,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 2.5, completionPerMillion: 10.0 },
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: PROVIDERS.OPENAI,
    capabilities: [MODEL_CATEGORIES.FAST, MODEL_CATEGORIES.GENERAL, MODEL_CATEGORIES.VISION],
    contextWindow: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.15, completionPerMillion: 0.6 },
  },
  {
    id: 'openai/o4-mini',
    name: 'o4-mini',
    provider: PROVIDERS.OPENAI,
    capabilities: [MODEL_CATEGORIES.CODE, MODEL_CATEGORIES.ANALYSIS, MODEL_CATEGORIES.GENERAL],
    contextWindow: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 1.1, completionPerMillion: 4.4 },
  },
  {
    id: 'google/gemini-2.5-pro-preview',
    name: 'Gemini 2.5 Pro',
    provider: PROVIDERS.GOOGLE,
    capabilities: [
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 1_048_576,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 1.25, completionPerMillion: 10.0 },
  },
  {
    id: 'google/gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: PROVIDERS.GOOGLE,
    capabilities: [MODEL_CATEGORIES.FAST, MODEL_CATEGORIES.GENERAL, MODEL_CATEGORIES.VISION],
    contextWindow: 1_048_576,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.075, completionPerMillion: 0.3 },
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    provider: PROVIDERS.META,
    capabilities: [MODEL_CATEGORIES.CODE, MODEL_CATEGORIES.GENERAL, MODEL_CATEGORIES.FAST],
    contextWindow: 131_072,
    supportsVision: false,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.12, completionPerMillion: 0.4 },
  },
  {
    id: 'meta-llama/llama-3.1-8b-instruct',
    name: 'Llama 3.1 8B',
    provider: PROVIDERS.META,
    capabilities: [MODEL_CATEGORIES.FAST],
    contextWindow: 131_072,
    supportsVision: false,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.06, completionPerMillion: 0.06 },
  },
] as const
