import {
  MODEL_CATEGORIES,
  MODEL_IDS,
  PROVIDERS,
} from './constants'
import type { ModelConfig } from '@/schemas/model'

const ONE_MILLION = 1_000_000 as const

export const STATIC_MODEL_REGISTRY: ReadonlyArray<ModelConfig> = [
  {
    id: MODEL_IDS.CLAUDE_SONNET_4,
    name: 'Claude Sonnet 4',
    provider: PROVIDERS.ANTHROPIC,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.CREATIVE,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 200 * ONE_MILLION,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 3, completionPerMillion: 15 },
  },
  {
    id: MODEL_IDS.CLAUDE_HAIKU_35,
    name: 'Claude 3.5 Haiku',
    provider: PROVIDERS.ANTHROPIC,
    capabilities: [MODEL_CATEGORIES.FAST, MODEL_CATEGORIES.GENERAL],
    contextWindow: 200 * ONE_MILLION,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.8, completionPerMillion: 4 },
  },
  {
    id: MODEL_IDS.GPT_4O,
    name: 'GPT-4o',
    provider: PROVIDERS.OPENAI,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.CREATIVE,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 5, completionPerMillion: 15 },
  },
  {
    id: MODEL_IDS.GPT_4O_MINI,
    name: 'GPT-4o Mini',
    provider: PROVIDERS.OPENAI,
    capabilities: [MODEL_CATEGORIES.FAST, MODEL_CATEGORIES.GENERAL],
    contextWindow: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.15, completionPerMillion: 0.6 },
  },
  {
    id: MODEL_IDS.GEMINI_25_PRO,
    name: 'Gemini 2.5 Pro',
    provider: PROVIDERS.GOOGLE,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: ONE_MILLION,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 3.5, completionPerMillion: 10.5 },
  },
  {
    id: MODEL_IDS.GEMINI_20_FLASH,
    name: 'Gemini 2.0 Flash',
    provider: PROVIDERS.GOOGLE,
    capabilities: [MODEL_CATEGORIES.FAST, MODEL_CATEGORIES.GENERAL],
    contextWindow: ONE_MILLION,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.35, completionPerMillion: 1.05 },
  },
  {
    id: MODEL_IDS.LLAMA_33_70B,
    name: 'Llama 3.3 70B Instruct',
    provider: PROVIDERS.META,
    capabilities: [MODEL_CATEGORIES.CODE, MODEL_CATEGORIES.GENERAL],
    contextWindow: 128_000,
    supportsVision: false,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.59, completionPerMillion: 0.79 },
  },
  {
    id: MODEL_IDS.LLAMA_31_8B,
    name: 'Llama 3.1 8B Instruct',
    provider: PROVIDERS.META,
    capabilities: [MODEL_CATEGORIES.FAST, MODEL_CATEGORIES.GENERAL],
    contextWindow: 128_000,
    supportsVision: false,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.08, completionPerMillion: 0.08 },
  },
]

