import { MODEL_CATEGORIES, MODEL_IDS, PROVIDERS } from './constants'

export const STATIC_MODELS = [
  {
    id: MODEL_IDS.CLAUDE_SONNET_4,
    name: 'Claude Sonnet 4',
    provider: PROVIDERS.ANTHROPIC,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.CREATIVE,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 200_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 3.0, completionPerMillion: 15.0 },
  },
  {
    id: MODEL_IDS.CLAUDE_HAIKU_35,
    name: 'Claude 3.5 Haiku',
    provider: PROVIDERS.ANTHROPIC,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.FAST,
      MODEL_CATEGORIES.GENERAL,
      MODEL_CATEGORIES.VISION,
    ],
    contextWindow: 200_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.8, completionPerMillion: 4.0 },
  },
  {
    id: MODEL_IDS.CLAUDE_OPUS_4,
    name: 'Claude Opus 4',
    provider: PROVIDERS.ANTHROPIC,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.CREATIVE,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 200_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 15.0, completionPerMillion: 75.0 },
  },
  {
    id: MODEL_IDS.GPT_4O,
    name: 'GPT-4o',
    provider: PROVIDERS.OPENAI,
    capabilities: [
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 2.5, completionPerMillion: 10.0 },
  },
  {
    id: MODEL_IDS.GPT_4O_MINI,
    name: 'GPT-4o Mini',
    provider: PROVIDERS.OPENAI,
    capabilities: [MODEL_CATEGORIES.FAST, MODEL_CATEGORIES.GENERAL, MODEL_CATEGORIES.VISION],
    contextWindow: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.15, completionPerMillion: 0.6 },
  },
  {
    id: MODEL_IDS.O4_MINI,
    name: 'o4-mini',
    provider: PROVIDERS.OPENAI,
    capabilities: [MODEL_CATEGORIES.CODE, MODEL_CATEGORIES.ANALYSIS, MODEL_CATEGORIES.GENERAL],
    contextWindow: 128_000,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 1.1, completionPerMillion: 4.4 },
  },
  {
    id: MODEL_IDS.GEMINI_25_PRO,
    name: 'Gemini 2.5 Pro',
    provider: PROVIDERS.GOOGLE,
    capabilities: [
      MODEL_CATEGORIES.ANALYSIS,
      MODEL_CATEGORIES.CODE,
      MODEL_CATEGORIES.VISION,
      MODEL_CATEGORIES.GENERAL,
    ],
    contextWindow: 1_048_576,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    pricing: { promptPerMillion: 1.25, completionPerMillion: 10.0 },
  },
  {
    id: MODEL_IDS.GEMINI_20_FLASH,
    name: 'Gemini 2.0 Flash',
    provider: PROVIDERS.GOOGLE,
    capabilities: [MODEL_CATEGORIES.FAST, MODEL_CATEGORIES.GENERAL, MODEL_CATEGORIES.VISION],
    contextWindow: 1_048_576,
    supportsVision: true,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.075, completionPerMillion: 0.3 },
  },
  {
    id: MODEL_IDS.LLAMA_33_70B,
    name: 'Llama 3.3 70B',
    provider: PROVIDERS.META,
    capabilities: [MODEL_CATEGORIES.CODE, MODEL_CATEGORIES.GENERAL, MODEL_CATEGORIES.FAST],
    contextWindow: 131_072,
    supportsVision: false,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.12, completionPerMillion: 0.4 },
  },
  {
    id: MODEL_IDS.LLAMA_31_8B,
    name: 'Llama 3.1 8B',
    provider: PROVIDERS.META,
    capabilities: [MODEL_CATEGORIES.FAST],
    contextWindow: 131_072,
    supportsVision: false,
    supportsTools: true,
    supportsThinking: false,
    pricing: { promptPerMillion: 0.06, completionPerMillion: 0.06 },
  },
] as const
